# Generated by Django 6.0.6 on 2026-09-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
    ]
