# Generated by Django 6.0.6 on 2026-09-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_paciente_primeiro_acesso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='psicologo',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Psicólogo', 'verbose_name_plural': 'Psicólogos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='notificacao_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('Solicitado Cancelamento', 'Solicitado Cancelamento')], default='AGENDADO', max_length=30),
        ),
    ]
