# Generated by Django 6.0.6 on 2026-09-29 00:26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_options_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacao',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
